server:
  port: 3344
spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: git@github.com:lcy-d/www.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
            - www
      ####读取分支
      label: master
  #rabbitmq相关配置
  rabbitmq:
    host: 192.168.202.101
    port: 5672
    username: admin
    password: admin
#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
##rabbitmq相关配置,暴露bus刷新配置的端点
management: # 暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: "bus-refresh"


